### ISSUE TITLE
Cannot register vault-plugin-auth-kubernetes plugin

### ISSUE THREAD

**Issue by kelseyhightower** [hashicorp/vault-plugin-auth-kubernetes#5] opened 2017-09-19 10:15 UTC
## Environment

I'm running on GKE; Kubernetes 1.7.5

Steps to reproduce:

I'm deploying vault 8.2 with the following StatefulSet, which downloads the plugin using an init container: https://gist.github.com/kelseyhightower/f90929935d52144b74a7380404d78e8a

Here is my vault config that configures the plugin directory:

```
disable_mlock = true

listener "tcp" {
      address = "0.0.0.0:8200"
      tls_cert_file = "/etc/vault/tls/vault.pem"
      tls_client_ca_file = "/etc/vault/tls/ca.pem"
      tls_key_file = "/etc/vault/tls/vault-key.pem"
      tls_min_version = "tls12"
      tls_require_and_verify_client_cert = "false"
}

plugin_directory = "/usr/local/libexec/vault"

storage "consul" {
      address = "127.0.0.1:8500"
      path = "vault/"
}
```

## How I Enabled the Plugin

```
vault write sys/plugins/catalog/kubernetes \
  sha_256=7da474c70fd4d3ce14508fd19a4cae8160e1f47ebe365e077fd0f8094d1dfacb \
  command="vault-plugin-auth-kubernetes"
```

```
Success! Data written to: sys/plugins/catalog/kubernetes
```

Next configure the plugin

```
vault write auth/kubernetes/config \
  kubernetes_host=https://35.197.84.128 \
  kubernetes_ca_cert=@ca.cert
```
```
Error writing data to auth/kubernetes/config: Error making API request.

URL: PUT https://35.203.143.169:8200/v1/auth/kubernetes/config
Code: 500. Errors:

* 1 error occurred:

* internal error
```

Reviewing the logs:

```
kubectl logs vault-0 vault
```

```
2017/09/19 10:09:46.119519 [ERROR] core: failed to run existence check: error=plugin exited before we could connect
2017/09/19 10:10:19.565675 [INFO ] expiration: revoked lease: lease_id=sys/wrapping/wrap/c2f3825192a5798055baee43902d43c9d4001bdd
2017/09/19 10:10:19 http: TLS handshake error from 10.16.4.5:38898: remote error: tls: bad certificate
2017/09/19 10:10:19.685566 [ERROR] plugin.vault-plugin-auth-kubernetes: plugin tls init: error="error during token unwrap request: secret is nil"
2017/09/19 10:10:19.686531 [ERROR] rollback: error rolling back: path=auth/kubernetes/ error=plugin exited before we could connect
2017/09/19 10:10:45.978640 [INFO ] expiration: revoked lease: lease_id=sys/wrapping/wrap/f271ef2d3f59a6018d7900be22293f2957676773
```

> 10.16.4.5 is the IP address of the Pod where vault is running and where the plugin is installed.

I'm running vault with TLS enable and the certificate was generated like this: https://github.com/kelseyhightower/nomad-on-kubernetes/blob/master/docs/04-nomad-infrastructure.md#setup-pki-infrastructure

Notice that the Pod IP address is not included in the TLS cert created for vault as all client use the external IP assigned to Vault. Is the plugin attempted to validate the Vault TLS cert using the local IP address assigned to Vault?

**Comment by briankassouf** [comment] 2017-09-26 02:16
Going to close this since the above command should have fixed the issue

**Closed by briankassouf** 2017-09-26 02:16 UTC

**Comment by bernielomax** [comment] 2017-10-23 00:38
I am getting the same issue as @kelseyhightower even with valid certificates defined. My plugin is just a copy of the mock plugin in vault source. I can confirm that the client certificates do work using environment variables against the vault client. Perhaps my issue is with the plugin itself and not the certs?

**Comment by jefferai** [comment] 2017-10-23 00:43
If you are having issues with a custom plugin, please raise an issue against the main Vault repo.
